### ISSUE TITLE
Plugin flagged as potentially not maintained

### ISSUE THREAD

**Issue by MikkCZ** [coffee2code/remember-me-controls#1]
It is mentioned at https://wordpress.org/support/topic/plugin-flagged-by-wordfence-scan-2/ and I can confirm, that Wordfence reports the "Remember Me Controls" plugins because it was not updated for a long time. The official listing https://wordpress.org/plugins/remember-me-controls/ shows a warning as well.

If the plugin is still maintained (even thought feature complete), it should be enough to update the `Tested up to` info.

**Comment by coffee2code** [comment]
@MikkCZ Thanks for the nudge! I had been working on some updates somewhat recently. I've now wrapped up those changes, so v2.0 is imminent.
